// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PersonRegister.Impl.Context;
using System;

namespace PersonRegister.Impl.Migrations
{
    [DbContext(typeof(PersonDataContext))]
    [Migration("20180322013308_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PersonRegister.Domain.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Complement")
                        .IsRequired()
                        .HasColumnName("COMPLEMENT");

                    b.Property<string>("Name")
                        .HasColumnName("NAME")
                        .HasMaxLength(400);

                    b.Property<int>("Number")
                        .HasColumnName("NUMBER");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnName("POSTAL_CODE")
                        .HasMaxLength(40);

                    b.HasKey("Id");

                    b.ToTable("ADDRESS");
                });

            modelBuilder.Entity("PersonRegister.Domain.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddressId");

                    b.Property<bool>("Gender")
                        .HasColumnName("GENDER")
                        .HasMaxLength(40);

                    b.Property<string>("IndentificationDocument")
                        .IsRequired()
                        .HasColumnName("INDENTIFICATION_DOCUMENT");

                    b.Property<string>("Name")
                        .HasColumnName("NAME")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("PERSON");
                });

            modelBuilder.Entity("PersonRegister.Domain.Entities.Person", b =>
                {
                    b.HasOne("PersonRegister.Domain.Entities.Address", "Address")
                        .WithMany("People")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
